// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DataTableController from "./data_table_controller.js"
application.register("data-table", DataTableController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import InfiniteScrollController from "./infinite_scroll_controller.js"
application.register("infinite-scroll", InfiniteScrollController)
